// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package trezor

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
// const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Type of failures returned by Failure message
// @used_in Failure
type FailureType int32

const (
	FailureType_Failure_UnexpectedMessage FailureType = 0
	FailureType_Failure_ButtonExpected    FailureType = 2
	FailureType_Failure_DataError         FailureType = 3
	FailureType_Failure_ActionCancelled   FailureType = 4
	FailureType_Failure_PinExpected       FailureType = 5
	FailureType_Failure_PinCancelled      FailureType = 6
	FailureType_Failure_PinInvalid        FailureType = 7
	FailureType_Failure_InvalidSignature  FailureType = 8
	FailureType_Failure_ProcessError      FailureType = 9
	FailureType_Failure_NotEnoughFunds    FailureType = 10
	FailureType_Failure_NotInitialized    FailureType = 11
	FailureType_Failure_FirmwareError     FailureType = 99
)

var FailureType_name = map[int32]string{
	0:  "Failure_UnexpectedMessage",
	2:  "Failure_ButtonExpected",
	3:  "Failure_DataError",
	4:  "Failure_ActionCancelled",
	5:  "Failure_PinExpected",
	6:  "Failure_PinCancelled",
	7:  "Failure_PinInvalid",
	8:  "Failure_InvalidSignature",
	9:  "Failure_ProcessError",
	10: "Failure_NotEnoughFunds",
	11: "Failure_NotInitialized",
	99: "Failure_FirmwareError",
}

var FailureType_value = map[string]int32{
	"Failure_UnexpectedMessage": 0,
	"Failure_ButtonExpected":    2,
	"Failure_DataError":         3,
	"Failure_ActionCancelled":   4,
	"Failure_PinExpected":       5,
	"Failure_PinCancelled":      6,
	"Failure_PinInvalid":        7,
	"Failure_InvalidSignature":  8,
	"Failure_ProcessError":      9,
	"Failure_NotEnoughFunds":    10,
	"Failure_NotInitialized":    11,
	"Failure_FirmwareError":     99,
}

func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}

func (FailureType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

//*
// Type of script which will be used for transaction output
// @used_in TxOutputType
type OutputScriptType int32

const (
	OutputScriptType_PAYTOADDRESS     OutputScriptType = 0
	OutputScriptType_PAYTOSCRIPTHASH  OutputScriptType = 1
	OutputScriptType_PAYTOMULTISIG    OutputScriptType = 2
	OutputScriptType_PAYTOOPRETURN    OutputScriptType = 3
	OutputScriptType_PAYTOWITNESS     OutputScriptType = 4
	OutputScriptType_PAYTOP2SHWITNESS OutputScriptType = 5
)

var OutputScriptType_name = map[int32]string{
	0: "PAYTOADDRESS",
	1: "PAYTOSCRIPTHASH",
	2: "PAYTOMULTISIG",
	3: "PAYTOOPRETURN",
	4: "PAYTOWITNESS",
	5: "PAYTOP2SHWITNESS",
}

var OutputScriptType_value = map[string]int32{
	"PAYTOADDRESS":     0,
	"PAYTOSCRIPTHASH":  1,
	"PAYTOMULTISIG":    2,
	"PAYTOOPRETURN":    3,
	"PAYTOWITNESS":     4,
	"PAYTOP2SHWITNESS": 5,
}

func (x OutputScriptType) String() string {
	return proto.EnumName(OutputScriptType_name, int32(x))
}

func (OutputScriptType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

//*
// Type of script which will be used for transaction output
// @used_in TxInputType
type InputScriptType int32

const (
	InputScriptType_SPENDADDRESS     InputScriptType = 0
	InputScriptType_SPENDMULTISIG    InputScriptType = 1
	InputScriptType_EXTERNAL         InputScriptType = 2
	InputScriptType_SPENDWITNESS     InputScriptType = 3
	InputScriptType_SPENDP2SHWITNESS InputScriptType = 4
)

var InputScriptType_name = map[int32]string{
	0: "SPENDADDRESS",
	1: "SPENDMULTISIG",
	2: "EXTERNAL",
	3: "SPENDWITNESS",
	4: "SPENDP2SHWITNESS",
}

var InputScriptType_value = map[string]int32{
	"SPENDADDRESS":     0,
	"SPENDMULTISIG":    1,
	"EXTERNAL":         2,
	"SPENDWITNESS":     3,
	"SPENDP2SHWITNESS": 4,
}

func (x InputScriptType) String() string {
	return proto.EnumName(InputScriptType_name, int32(x))
}

func (InputScriptType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

//*
// Type of information by transaction signing process
// @used_in TxRequest
type RequestType int32

const (
	RequestType_TXINPUT     RequestType = 0
	RequestType_TXOUTPUT    RequestType = 1
	RequestType_TXMETA      RequestType = 2
	RequestType_TXFINISHED  RequestType = 3
	RequestType_TXEXTRADATA RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "TXINPUT",
	1: "TXOUTPUT",
	2: "TXMETA",
	3: "TXFINISHED",
	4: "TXEXTRADATA",
}

var RequestType_value = map[string]int32{
	"TXINPUT":     0,
	"TXOUTPUT":    1,
	"TXMETA":      2,
	"TXFINISHED":  3,
	"TXEXTRADATA": 4,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

//*
// Type of button request
// @used_in ButtonRequest
type ButtonRequestType int32

const (
	ButtonRequestType_ButtonRequest_Other            ButtonRequestType = 0
	ButtonRequestType_ButtonRequest_FeeOverThreshold ButtonRequestType = 2
	ButtonRequestType_ButtonRequest_ConfirmOutput    ButtonRequestType = 3
	ButtonRequestType_ButtonRequest_ResetDevice      ButtonRequestType = 4
	ButtonRequestType_ButtonRequest_ConfirmWord      ButtonRequestType = 5
	ButtonRequestType_ButtonRequest_WipeDevice       ButtonRequestType = 6
	ButtonRequestType_ButtonRequest_ProtectCall      ButtonRequestType = 7
	ButtonRequestType_ButtonRequest_SignTx           ButtonRequestType = 8
	ButtonRequestType_ButtonRequest_FirmwareCheck    ButtonRequestType = 9
	ButtonRequestType_ButtonRequest_Address          ButtonRequestType = 10
	ButtonRequestType_ButtonRequest_PublicKey        ButtonRequestType = 11
)

var ButtonRequestType_name = map[int32]string{
	0:  "ButtonRequest_Other",
	2:  "ButtonRequest_FeeOverThreshold",
	3:  "ButtonRequest_ConfirmOutput",
	4:  "ButtonRequest_ResetDevice",
	5:  "ButtonRequest_ConfirmWord",
	6:  "ButtonRequest_WipeDevice",
	7:  "ButtonRequest_ProtectCall",
	8:  "ButtonRequest_SignTx",
	9:  "ButtonRequest_FirmwareCheck",
	10: "ButtonRequest_Address",
	11: "ButtonRequest_PublicKey",
}

var ButtonRequestType_value = map[string]int32{
	"ButtonRequest_Other":            0,
	"ButtonRequest_FeeOverThreshold": 2,
	"ButtonRequest_ConfirmOutput":    3,
	"ButtonRequest_ResetDevice":      4,
	"ButtonRequest_ConfirmWord":      5,
	"ButtonRequest_WipeDevice":       6,
	"ButtonRequest_ProtectCall":      7,
	"ButtonRequest_SignTx":           8,
	"ButtonRequest_FirmwareCheck":    9,
	"ButtonRequest_Address":          10,
	"ButtonRequest_PublicKey":        11,
}

func (x ButtonRequestType) String() string {
	return proto.EnumName(ButtonRequestType_name, int32(x))
}

func (ButtonRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

//*
// Type of PIN request
// @used_in PinMatrixRequest
type PinMatrixRequestType int32

const (
	PinMatrixRequestType_PinMatrixRequestType_Current   PinMatrixRequestType = 0
	PinMatrixRequestType_PinMatrixRequestType_NewFirst  PinMatrixRequestType = 2
	PinMatrixRequestType_PinMatrixRequestType_NewSecond PinMatrixRequestType = 3
)

var PinMatrixRequestType_name = map[int32]string{
	0: "PinMatrixRequestType_Current",
	2: "PinMatrixRequestType_NewFirst",
	3: "PinMatrixRequestType_NewSecond",
}

var PinMatrixRequestType_value = map[string]int32{
	"PinMatrixRequestType_Current":   0,
	"PinMatrixRequestType_NewFirst":  2,
	"PinMatrixRequestType_NewSecond": 3,
}

func (x PinMatrixRequestType) String() string {
	return proto.EnumName(PinMatrixRequestType_name, int32(x))
}

func (PinMatrixRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

//*
// Type of recovery procedure. These should be used as bitmask, e.g.,
// `RecoveryDeviceType_ScrambledWords | RecoveryDeviceType_Matrix`
// listing every method supported by the host computer.
//
// Note that ScrambledWords must be supported by every implementation
// for backward compatibility; there is no way to not support it.
//
// @used_in RecoveryDevice
type RecoveryDeviceType int32

const (
	// use powers of two when extending this field
	RecoveryDeviceType_RecoveryDeviceType_ScrambledWords RecoveryDeviceType = 0
	RecoveryDeviceType_RecoveryDeviceType_Matrix         RecoveryDeviceType = 1
)

var RecoveryDeviceType_name = map[int32]string{
	0: "RecoveryDeviceType_ScrambledWords",
	1: "RecoveryDeviceType_Matrix",
}

var RecoveryDeviceType_value = map[string]int32{
	"RecoveryDeviceType_ScrambledWords": 0,
	"RecoveryDeviceType_Matrix":         1,
}

func (x RecoveryDeviceType) String() string {
	return proto.EnumName(RecoveryDeviceType_name, int32(x))
}

func (RecoveryDeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

//*
// Type of Recovery Word request
// @used_in WordRequest
type WordRequestType int32

const (
	WordRequestType_WordRequestType_Plain   WordRequestType = 0
	WordRequestType_WordRequestType_Matrix9 WordRequestType = 1
	WordRequestType_WordRequestType_Matrix6 WordRequestType = 2
)

var WordRequestType_name = map[int32]string{
	0: "WordRequestType_Plain",
	1: "WordRequestType_Matrix9",
	2: "WordRequestType_Matrix6",
}

var WordRequestType_value = map[string]int32{
	"WordRequestType_Plain":   0,
	"WordRequestType_Matrix9": 1,
	"WordRequestType_Matrix6": 2,
}

func (x WordRequestType) String() string {
	return proto.EnumName(WordRequestType_name, int32(x))
}

func (WordRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

//*
// Structure representing BIP32 (hierarchical deterministic) node
// Used for imports of private key into the device and exporting public key out of device
// @used_in PublicKey
// @used_in LoadDevice
// @used_in DebugLinkState
// @used_in Storage
type HDNodeType struct {
	Depth                uint32   `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Fingerprint          uint32   `protobuf:"varint,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ChildNum             uint32   `protobuf:"varint,3,opt,name=child_num,json=childNum,proto3" json:"child_num,omitempty"`
	ChainCode            []byte   `protobuf:"bytes,4,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HDNodeType) Reset()         { *m = HDNodeType{} }
func (m *HDNodeType) String() string { return proto.CompactTextString(m) }
func (*HDNodeType) ProtoMessage()    {}
func (*HDNodeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *HDNodeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HDNodeType.Unmarshal(m, b)
}
func (m *HDNodeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HDNodeType.Marshal(b, m, deterministic)
}
func (m *HDNodeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HDNodeType.Merge(m, src)
}
func (m *HDNodeType) XXX_Size() int {
	return xxx_messageInfo_HDNodeType.Size(m)
}
func (m *HDNodeType) XXX_DiscardUnknown() {
	xxx_messageInfo_HDNodeType.DiscardUnknown(m)
}

var xxx_messageInfo_HDNodeType proto.InternalMessageInfo

func (m *HDNodeType) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *HDNodeType) GetFingerprint() uint32 {
	if m != nil {
		return m.Fingerprint
	}
	return 0
}

func (m *HDNodeType) GetChildNum() uint32 {
	if m != nil {
		return m.ChildNum
	}
	return 0
}

func (m *HDNodeType) GetChainCode() []byte {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

func (m *HDNodeType) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HDNodeType) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HDNodePathType struct {
	Node                 *HDNodeType `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	AddressN             []uint32    `protobuf:"varint,2,rep,packed,name=address_n,json=addressN,proto3" json:"address_n,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HDNodePathType) Reset()         { *m = HDNodePathType{} }
func (m *HDNodePathType) String() string { return proto.CompactTextString(m) }
func (*HDNodePathType) ProtoMessage()    {}
func (*HDNodePathType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *HDNodePathType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HDNodePathType.Unmarshal(m, b)
}
func (m *HDNodePathType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HDNodePathType.Marshal(b, m, deterministic)
}
func (m *HDNodePathType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HDNodePathType.Merge(m, src)
}
func (m *HDNodePathType) XXX_Size() int {
	return xxx_messageInfo_HDNodePathType.Size(m)
}
func (m *HDNodePathType) XXX_DiscardUnknown() {
	xxx_messageInfo_HDNodePathType.DiscardUnknown(m)
}

var xxx_messageInfo_HDNodePathType proto.InternalMessageInfo

func (m *HDNodePathType) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HDNodePathType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

//*
// Structure representing Coin
// @used_in Features
type CoinType struct {
	CoinName             string   `protobuf:"bytes,1,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	CoinShortcut         string   `protobuf:"bytes,2,opt,name=coin_shortcut,json=coinShortcut,proto3" json:"coin_shortcut,omitempty"`
	AddressType          uint32   `protobuf:"varint,3,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	MaxfeeKb             uint64   `protobuf:"varint,4,opt,name=maxfee_kb,json=maxfeeKb,proto3" json:"maxfee_kb,omitempty"`
	AddressTypeP2Sh      uint32   `protobuf:"varint,5,opt,name=address_type_p2sh,json=addressTypeP2sh,proto3" json:"address_type_p2sh,omitempty"`
	SignedMessageHeader  string   `protobuf:"bytes,8,opt,name=signed_message_header,json=signedMessageHeader,proto3" json:"signed_message_header,omitempty"`
	XpubMagic            uint32   `protobuf:"varint,9,opt,name=xpub_magic,json=xpubMagic,proto3" json:"xpub_magic,omitempty"`
	XprvMagic            uint32   `protobuf:"varint,10,opt,name=xprv_magic,json=xprvMagic,proto3" json:"xprv_magic,omitempty"`
	Segwit               bool     `protobuf:"varint,11,opt,name=segwit,proto3" json:"segwit,omitempty"`
	Forkid               uint32   `protobuf:"varint,12,opt,name=forkid,proto3" json:"forkid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinType) Reset()         { *m = CoinType{} }
func (m *CoinType) String() string { return proto.CompactTextString(m) }
func (*CoinType) ProtoMessage()    {}
func (*CoinType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *CoinType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinType.Unmarshal(m, b)
}
func (m *CoinType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinType.Marshal(b, m, deterministic)
}
func (m *CoinType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinType.Merge(m, src)
}
func (m *CoinType) XXX_Size() int {
	return xxx_messageInfo_CoinType.Size(m)
}
func (m *CoinType) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinType.DiscardUnknown(m)
}

var xxx_messageInfo_CoinType proto.InternalMessageInfo

func (m *CoinType) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *CoinType) GetCoinShortcut() string {
	if m != nil {
		return m.CoinShortcut
	}
	return ""
}

func (m *CoinType) GetAddressType() uint32 {
	if m != nil {
		return m.AddressType
	}
	return 0
}

func (m *CoinType) GetMaxfeeKb() uint64 {
	if m != nil {
		return m.MaxfeeKb
	}
	return 0
}

func (m *CoinType) GetAddressTypeP2Sh() uint32 {
	if m != nil {
		return m.AddressTypeP2Sh
	}
	return 0
}

func (m *CoinType) GetSignedMessageHeader() string {
	if m != nil {
		return m.SignedMessageHeader
	}
	return ""
}

func (m *CoinType) GetXpubMagic() uint32 {
	if m != nil {
		return m.XpubMagic
	}
	return 0
}

func (m *CoinType) GetXprvMagic() uint32 {
	if m != nil {
		return m.XprvMagic
	}
	return 0
}

func (m *CoinType) GetSegwit() bool {
	if m != nil {
		return m.Segwit
	}
	return false
}

func (m *CoinType) GetForkid() uint32 {
	if m != nil {
		return m.Forkid
	}
	return 0
}

//*
// Type of redeem script used in input
// @used_in TxInputType
type MultisigRedeemScriptType struct {
	Pubkeys              []*HDNodePathType `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	Signatures           [][]byte          `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	M                    uint32            `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MultisigRedeemScriptType) Reset()         { *m = MultisigRedeemScriptType{} }
func (m *MultisigRedeemScriptType) String() string { return proto.CompactTextString(m) }
func (*MultisigRedeemScriptType) ProtoMessage()    {}
func (*MultisigRedeemScriptType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *MultisigRedeemScriptType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultisigRedeemScriptType.Unmarshal(m, b)
}
func (m *MultisigRedeemScriptType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultisigRedeemScriptType.Marshal(b, m, deterministic)
}
func (m *MultisigRedeemScriptType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultisigRedeemScriptType.Merge(m, src)
}
func (m *MultisigRedeemScriptType) XXX_Size() int {
	return xxx_messageInfo_MultisigRedeemScriptType.Size(m)
}
func (m *MultisigRedeemScriptType) XXX_DiscardUnknown() {
	xxx_messageInfo_MultisigRedeemScriptType.DiscardUnknown(m)
}

var xxx_messageInfo_MultisigRedeemScriptType proto.InternalMessageInfo

func (m *MultisigRedeemScriptType) GetPubkeys() []*HDNodePathType {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetM() uint32 {
	if m != nil {
		return m.M
	}
	return 0
}

//*
// Structure representing transaction input
// @used_in SimpleSignTx
// @used_in TransactionType
type TxInputType struct {
	AddressN             []uint32                  `protobuf:"varint,1,rep,packed,name=address_n,json=addressN,proto3" json:"address_n,omitempty"`
	PrevHash             []byte                    `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	PrevIndex            uint32                    `protobuf:"varint,3,opt,name=prev_index,json=prevIndex,proto3" json:"prev_index,omitempty"`
	ScriptSig            []byte                    `protobuf:"bytes,4,opt,name=script_sig,json=scriptSig,proto3" json:"script_sig,omitempty"`
	Sequence             uint32                    `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ScriptType           InputScriptType           `protobuf:"varint,6,opt,name=script_type,json=scriptType,proto3,enum=trezor.InputScriptType" json:"script_type,omitempty"`
	Multisig             *MultisigRedeemScriptType `protobuf:"bytes,7,opt,name=multisig,proto3" json:"multisig,omitempty"`
	Amount               uint64                    `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TxInputType) Reset()         { *m = TxInputType{} }
func (m *TxInputType) String() string { return proto.CompactTextString(m) }
func (*TxInputType) ProtoMessage()    {}
func (*TxInputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *TxInputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInputType.Unmarshal(m, b)
}
func (m *TxInputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInputType.Marshal(b, m, deterministic)
}
func (m *TxInputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInputType.Merge(m, src)
}
func (m *TxInputType) XXX_Size() int {
	return xxx_messageInfo_TxInputType.Size(m)
}
func (m *TxInputType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInputType.DiscardUnknown(m)
}

var xxx_messageInfo_TxInputType proto.InternalMessageInfo

func (m *TxInputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxInputType) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxInputType) GetPrevIndex() uint32 {
	if m != nil {
		return m.PrevIndex
	}
	return 0
}

func (m *TxInputType) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *TxInputType) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *TxInputType) GetScriptType() InputScriptType {
	if m != nil {
		return m.ScriptType
	}
	return InputScriptType_SPENDADDRESS
}

func (m *TxInputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxInputType) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

//*
// Structure representing transaction output
// @used_in SimpleSignTx
// @used_in TransactionType
type TxOutputType struct {
	Address              string                    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AddressN             []uint32                  `protobuf:"varint,2,rep,packed,name=address_n,json=addressN,proto3" json:"address_n,omitempty"`
	Amount               uint64                    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ScriptType           OutputScriptType          `protobuf:"varint,4,opt,name=script_type,json=scriptType,proto3,enum=trezor.OutputScriptType" json:"script_type,omitempty"`
	Multisig             *MultisigRedeemScriptType `protobuf:"bytes,5,opt,name=multisig,proto3" json:"multisig,omitempty"`
	OpReturnData         []byte                    `protobuf:"bytes,6,opt,name=op_return_data,json=opReturnData,proto3" json:"op_return_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TxOutputType) Reset()         { *m = TxOutputType{} }
func (m *TxOutputType) String() string { return proto.CompactTextString(m) }
func (*TxOutputType) ProtoMessage()    {}
func (*TxOutputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *TxOutputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutputType.Unmarshal(m, b)
}
func (m *TxOutputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutputType.Marshal(b, m, deterministic)
}
func (m *TxOutputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutputType.Merge(m, src)
}
func (m *TxOutputType) XXX_Size() int {
	return xxx_messageInfo_TxOutputType.Size(m)
}
func (m *TxOutputType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutputType.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutputType proto.InternalMessageInfo

func (m *TxOutputType) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TxOutputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxOutputType) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TxOutputType) GetScriptType() OutputScriptType {
	if m != nil {
		return m.ScriptType
	}
	return OutputScriptType_PAYTOADDRESS
}

func (m *TxOutputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxOutputType) GetOpReturnData() []byte {
	if m != nil {
		return m.OpReturnData
	}
	return nil
}

//*
// Structure representing compiled transaction output
// @used_in TransactionType
type TxOutputBinType struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ScriptPubkey         []byte   `protobuf:"bytes,2,opt,name=script_pubkey,json=scriptPubkey,proto3" json:"script_pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutputBinType) Reset()         { *m = TxOutputBinType{} }
func (m *TxOutputBinType) String() string { return proto.CompactTextString(m) }
func (*TxOutputBinType) ProtoMessage()    {}
func (*TxOutputBinType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *TxOutputBinType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutputBinType.Unmarshal(m, b)
}
func (m *TxOutputBinType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutputBinType.Marshal(b, m, deterministic)
}
func (m *TxOutputBinType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutputBinType.Merge(m, src)
}
func (m *TxOutputBinType) XXX_Size() int {
	return xxx_messageInfo_TxOutputBinType.Size(m)
}
func (m *TxOutputBinType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutputBinType.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutputBinType proto.InternalMessageInfo

func (m *TxOutputBinType) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TxOutputBinType) GetScriptPubkey() []byte {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

//*
// Structure representing transaction
// @used_in SimpleSignTx
type TransactionType struct {
	Version              uint32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Inputs               []*TxInputType     `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	BinOutputs           []*TxOutputBinType `protobuf:"bytes,3,rep,name=bin_outputs,json=binOutputs,proto3" json:"bin_outputs,omitempty"`
	Outputs              []*TxOutputType    `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	LockTime             uint32             `protobuf:"varint,4,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	InputsCnt            uint32             `protobuf:"varint,6,opt,name=inputs_cnt,json=inputsCnt,proto3" json:"inputs_cnt,omitempty"`
	OutputsCnt           uint32             `protobuf:"varint,7,opt,name=outputs_cnt,json=outputsCnt,proto3" json:"outputs_cnt,omitempty"`
	ExtraData            []byte             `protobuf:"bytes,8,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	ExtraDataLen         uint32             `protobuf:"varint,9,opt,name=extra_data_len,json=extraDataLen,proto3" json:"extra_data_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionType) Reset()         { *m = TransactionType{} }
func (m *TransactionType) String() string { return proto.CompactTextString(m) }
func (*TransactionType) ProtoMessage()    {}
func (*TransactionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *TransactionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionType.Unmarshal(m, b)
}
func (m *TransactionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionType.Marshal(b, m, deterministic)
}
func (m *TransactionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionType.Merge(m, src)
}
func (m *TransactionType) XXX_Size() int {
	return xxx_messageInfo_TransactionType.Size(m)
}
func (m *TransactionType) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionType.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionType proto.InternalMessageInfo

func (m *TransactionType) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TransactionType) GetInputs() []*TxInputType {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionType) GetBinOutputs() []*TxOutputBinType {
	if m != nil {
		return m.BinOutputs
	}
	return nil
}

func (m *TransactionType) GetOutputs() []*TxOutputType {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *TransactionType) GetLockTime() uint32 {
	if m != nil {
		return m.LockTime
	}
	return 0
}

func (m *TransactionType) GetInputsCnt() uint32 {
	if m != nil {
		return m.InputsCnt
	}
	return 0
}

func (m *TransactionType) GetOutputsCnt() uint32 {
	if m != nil {
		return m.OutputsCnt
	}
	return 0
}

func (m *TransactionType) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *TransactionType) GetExtraDataLen() uint32 {
	if m != nil {
		return m.ExtraDataLen
	}
	return 0
}

//*
// Structure representing request details
// @used_in TxRequest
type TxRequestDetailsType struct {
	RequestIndex         uint32   `protobuf:"varint,1,opt,name=request_index,json=requestIndex,proto3" json:"request_index,omitempty"`
	TxHash               []byte   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ExtraDataLen         uint32   `protobuf:"varint,3,opt,name=extra_data_len,json=extraDataLen,proto3" json:"extra_data_len,omitempty"`
	ExtraDataOffset      uint32   `protobuf:"varint,4,opt,name=extra_data_offset,json=extraDataOffset,proto3" json:"extra_data_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequestDetailsType) Reset()         { *m = TxRequestDetailsType{} }
func (m *TxRequestDetailsType) String() string { return proto.CompactTextString(m) }
func (*TxRequestDetailsType) ProtoMessage()    {}
func (*TxRequestDetailsType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *TxRequestDetailsType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequestDetailsType.Unmarshal(m, b)
}
func (m *TxRequestDetailsType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequestDetailsType.Marshal(b, m, deterministic)
}
func (m *TxRequestDetailsType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequestDetailsType.Merge(m, src)
}
func (m *TxRequestDetailsType) XXX_Size() int {
	return xxx_messageInfo_TxRequestDetailsType.Size(m)
}
func (m *TxRequestDetailsType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequestDetailsType.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequestDetailsType proto.InternalMessageInfo

func (m *TxRequestDetailsType) GetRequestIndex() uint32 {
	if m != nil {
		return m.RequestIndex
	}
	return 0
}

func (m *TxRequestDetailsType) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxRequestDetailsType) GetExtraDataLen() uint32 {
	if m != nil {
		return m.ExtraDataLen
	}
	return 0
}

func (m *TxRequestDetailsType) GetExtraDataOffset() uint32 {
	if m != nil {
		return m.ExtraDataOffset
	}
	return 0
}

//*
// Structure representing serialized data
// @used_in TxRequest
type TxRequestSerializedType struct {
	SignatureIndex       uint32   `protobuf:"varint,1,opt,name=signature_index,json=signatureIndex,proto3" json:"signature_index,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SerializedTx         []byte   `protobuf:"bytes,3,opt,name=serialized_tx,json=serializedTx,proto3" json:"serialized_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequestSerializedType) Reset()         { *m = TxRequestSerializedType{} }
func (m *TxRequestSerializedType) String() string { return proto.CompactTextString(m) }
func (*TxRequestSerializedType) ProtoMessage()    {}
func (*TxRequestSerializedType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *TxRequestSerializedType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequestSerializedType.Unmarshal(m, b)
}
func (m *TxRequestSerializedType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequestSerializedType.Marshal(b, m, deterministic)
}
func (m *TxRequestSerializedType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequestSerializedType.Merge(m, src)
}
func (m *TxRequestSerializedType) XXX_Size() int {
	return xxx_messageInfo_TxRequestSerializedType.Size(m)
}
func (m *TxRequestSerializedType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequestSerializedType.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequestSerializedType proto.InternalMessageInfo

func (m *TxRequestSerializedType) GetSignatureIndex() uint32 {
	if m != nil {
		return m.SignatureIndex
	}
	return 0
}

func (m *TxRequestSerializedType) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TxRequestSerializedType) GetSerializedTx() []byte {
	if m != nil {
		return m.SerializedTx
	}
	return nil
}

//*
// Structure representing identity data
// @used_in IdentityType
type IdentityType struct {
	Proto                string   `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Index                uint32   `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityType) Reset()         { *m = IdentityType{} }
func (m *IdentityType) String() string { return proto.CompactTextString(m) }
func (*IdentityType) ProtoMessage()    {}
func (*IdentityType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *IdentityType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityType.Unmarshal(m, b)
}
func (m *IdentityType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityType.Marshal(b, m, deterministic)
}
func (m *IdentityType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityType.Merge(m, src)
}
func (m *IdentityType) XXX_Size() int {
	return xxx_messageInfo_IdentityType.Size(m)
}
func (m *IdentityType) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityType.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityType proto.InternalMessageInfo

func (m *IdentityType) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *IdentityType) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *IdentityType) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *IdentityType) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *IdentityType) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *IdentityType) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "trezor.wire_in",
	Tag:           "varint,50002,opt,name=wire_in",
	Filename:      "types.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "trezor.wire_out",
	Tag:           "varint,50003,opt,name=wire_out",
	Filename:      "types.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "trezor.wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in",
	Filename:      "types.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "trezor.wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out",
	Filename:      "types.proto",
}

var E_WireTiny = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50006,
	Name:          "trezor.wire_tiny",
	Tag:           "varint,50006,opt,name=wire_tiny",
	Filename:      "types.proto",
}

var E_WireBootloader = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50007,
	Name:          "trezor.wire_bootloader",
	Tag:           "varint,50007,opt,name=wire_bootloader",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterEnum("trezor.FailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("trezor.OutputScriptType", OutputScriptType_name, OutputScriptType_value)
	proto.RegisterEnum("trezor.InputScriptType", InputScriptType_name, InputScriptType_value)
	proto.RegisterEnum("trezor.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("trezor.ButtonRequestType", ButtonRequestType_name, ButtonRequestType_value)
	proto.RegisterEnum("trezor.PinMatrixRequestType", PinMatrixRequestType_name, PinMatrixRequestType_value)
	proto.RegisterEnum("trezor.RecoveryDeviceType", RecoveryDeviceType_name, RecoveryDeviceType_value)
	proto.RegisterEnum("trezor.WordRequestType", WordRequestType_name, WordRequestType_value)
	proto.RegisterType((*HDNodeType)(nil), "trezor.HDNodeType")
	proto.RegisterType((*HDNodePathType)(nil), "trezor.HDNodePathType")
	proto.RegisterType((*CoinType)(nil), "trezor.CoinType")
	proto.RegisterType((*MultisigRedeemScriptType)(nil), "trezor.MultisigRedeemScriptType")
	proto.RegisterType((*TxInputType)(nil), "trezor.TxInputType")
	proto.RegisterType((*TxOutputType)(nil), "trezor.TxOutputType")
	proto.RegisterType((*TxOutputBinType)(nil), "trezor.TxOutputBinType")
	proto.RegisterType((*TransactionType)(nil), "trezor.TransactionType")
	proto.RegisterType((*TxRequestDetailsType)(nil), "trezor.TxRequestDetailsType")
	proto.RegisterType((*TxRequestSerializedType)(nil), "trezor.TxRequestSerializedType")
	proto.RegisterType((*IdentityType)(nil), "trezor.IdentityType")
	proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)
	proto.RegisterExtension(E_WireTiny)
	proto.RegisterExtension(E_WireBootloader)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x4b, 0x6f, 0x23, 0x49,
	0x1d, 0x4f, 0xdb, 0x4e, 0x6c, 0xff, 0x6d, 0xc7, 0x9d, 0x4a, 0x66, 0xd2, 0xf3, 0xda, 0xcd, 0x78,
	0x78, 0x8c, 0x82, 0x94, 0x85, 0x20, 0x21, 0x36, 0x5a, 0x21, 0x9c, 0xd8, 0xd9, 0x58, 0x33, 0x71,
	0xac, 0x76, 0x87, 0x09, 0x5c, 0x5a, 0xed, 0xee, 0x8a, 0x5d, 0x4a, 0xbb, 0xca, 0x54, 0x57, 0x67,
	0xec, 0xb9, 0x70, 0x02, 0x24, 0x3e, 0x08, 0x77, 0xbe, 0x01, 0x9f, 0x61, 0x79, 0x49, 0x5c, 0xb8,
	0xf0, 0x31, 0x38, 0xa0, 0x7a, 0xb4, 0x1f, 0xc9, 0x0c, 0x64, 0x6f, 0xae, 0xdf, 0xef, 0xff, 0x7e,
	0x54, 0x97, 0xa1, 0x22, 0x66, 0x13, 0x9c, 0x1c, 0x4c, 0x38, 0x13, 0x0c, 0x6d, 0x08, 0x8e, 0x3f,
	0x30, 0xfe, 0x74, 0x6f, 0xc8, 0xd8, 0x30, 0xc6, 0x5f, 0x28, 0x74, 0x90, 0x5e, 0x7f, 0x11, 0xe1,
	0x24, 0xe4, 0x64, 0x22, 0x18, 0xd7, 0x92, 0x8d, 0x3f, 0x5b, 0x00, 0x67, 0xad, 0x2e, 0x8b, 0xb0,
	0x37, 0x9b, 0x60, 0xb4, 0x03, 0xeb, 0x11, 0x9e, 0x88, 0x91, 0x63, 0xed, 0x59, 0xaf, 0x6b, 0xae,
	0x3e, 0xa0, 0x3d, 0xa8, 0x5c, 0x13, 0x3a, 0xc4, 0x7c, 0xc2, 0x09, 0x15, 0x4e, 0x4e, 0x71, 0xcb,
	0x10, 0x7a, 0x06, 0xe5, 0x70, 0x44, 0xe2, 0xc8, 0xa7, 0xe9, 0xd8, 0xc9, 0x2b, 0xbe, 0xa4, 0x80,
	0x6e, 0x3a, 0x46, 0x2f, 0x00, 0xc2, 0x51, 0x40, 0xa8, 0x1f, 0xb2, 0x08, 0x3b, 0x85, 0x3d, 0xeb,
	0x75, 0xd5, 0x2d, 0x2b, 0xe4, 0x84, 0x45, 0x18, 0x7d, 0x0e, 0x95, 0x09, 0x27, 0xb7, 0x81, 0xc0,
	0xfe, 0x0d, 0x9e, 0x39, 0xeb, 0x8a, 0x07, 0x03, 0xbd, 0xc1, 0x33, 0xa9, 0x3f, 0x49, 0x07, 0x31,
	0x09, 0x15, 0xbf, 0xa1, 0xf5, 0x35, 0xf2, 0x06, 0xcf, 0x1a, 0x97, 0xb0, 0xa9, 0x33, 0xe8, 0x05,
	0x62, 0xa4, 0xb2, 0xf8, 0x1e, 0x14, 0xa8, 0x74, 0x25, 0x93, 0xa8, 0x1c, 0xa2, 0x03, 0x5d, 0x8d,
	0x83, 0x45, 0x9e, 0xae, 0xe2, 0x65, 0xd4, 0x41, 0x14, 0x71, 0x9c, 0x24, 0x3e, 0x75, 0x72, 0x7b,
	0x79, 0x19, 0xb5, 0x01, 0xba, 0x8d, 0x7f, 0xe6, 0xa0, 0x74, 0xc2, 0x08, 0x55, 0x16, 0x65, 0x7e,
	0x8c, 0x50, 0x9f, 0x06, 0x63, 0x6d, 0xb6, 0xec, 0x96, 0x24, 0xd0, 0x0d, 0xc6, 0x18, 0xbd, 0x82,
	0x9a, 0x22, 0x93, 0x11, 0xe3, 0x22, 0x4c, 0x75, 0x81, 0xca, 0x6e, 0x55, 0x82, 0x7d, 0x83, 0xa1,
	0x97, 0x50, 0xcd, 0x7c, 0xc9, 0x4e, 0x99, 0x22, 0x55, 0x0c, 0x96, 0x39, 0x19, 0x07, 0xd3, 0x6b,
	0x8c, 0xfd, 0x9b, 0x81, 0x2a, 0x53, 0xc1, 0x2d, 0x69, 0xe0, 0xcd, 0x00, 0xed, 0xc3, 0xd6, 0xb2,
	0xbe, 0x3f, 0x39, 0x4c, 0x46, 0xaa, 0x56, 0x35, 0xb7, 0xbe, 0x64, 0xa4, 0x77, 0x98, 0x8c, 0xd0,
	0x21, 0x3c, 0x4a, 0xc8, 0x90, 0xe2, 0xc8, 0x1f, 0xe3, 0x24, 0x09, 0x86, 0xd8, 0x1f, 0xe1, 0x20,
	0xc2, 0xdc, 0x29, 0xa9, 0xc0, 0xb6, 0x35, 0x79, 0xae, 0xb9, 0x33, 0x45, 0xc9, 0x22, 0x4f, 0x27,
	0xe9, 0xc0, 0x1f, 0x07, 0x43, 0x12, 0x3a, 0x65, 0x65, 0xb8, 0x2c, 0x91, 0x73, 0x09, 0x68, 0x9a,
	0xdf, 0x1a, 0x1a, 0x32, 0x9a, 0xdf, 0x6a, 0xfa, 0x31, 0x6c, 0x24, 0x78, 0xf8, 0x9e, 0x08, 0xa7,
	0xb2, 0x67, 0xbd, 0x2e, 0xb9, 0xe6, 0x24, 0xf1, 0x6b, 0xc6, 0x6f, 0x48, 0xe4, 0x54, 0x95, 0x8a,
	0x39, 0x35, 0x3e, 0x80, 0x73, 0x9e, 0xc6, 0x82, 0x24, 0x64, 0xe8, 0xe2, 0x08, 0xe3, 0x71, 0x5f,
	0x8d, 0xa5, 0x2a, 0xc3, 0x0f, 0xa1, 0x38, 0x49, 0x07, 0x37, 0x78, 0x96, 0x38, 0xd6, 0x5e, 0xfe,
	0x75, 0xe5, 0xf0, 0xf1, 0x6a, 0x03, 0xb3, 0x36, 0xbb, 0x99, 0x18, 0xfa, 0x0c, 0x40, 0xa6, 0x14,
	0x88, 0x94, 0xe3, 0x44, 0x35, 0xb2, 0xea, 0x2e, 0x21, 0xa8, 0x0a, 0x56, 0x36, 0x95, 0xd6, 0xb8,
	0xf1, 0xa7, 0x1c, 0x54, 0xbc, 0x69, 0x87, 0x4e, 0x52, 0x91, 0x95, 0x7d, 0x31, 0x05, 0xd6, 0xea,
	0x14, 0x48, 0x72, 0xc2, 0xf1, 0xad, 0x3f, 0x0a, 0x92, 0x91, 0xea, 0x6b, 0xd5, 0x2d, 0x49, 0xe0,
	0x2c, 0x48, 0x46, 0x6a, 0x30, 0x25, 0x49, 0x68, 0x84, 0xa7, 0xc6, 0x81, 0x12, 0xef, 0x48, 0x40,
	0xd2, 0x7a, 0xdb, 0xfc, 0x84, 0x0c, 0xb3, 0xb9, 0xd7, 0x48, 0x9f, 0x0c, 0xd1, 0x53, 0x28, 0x25,
	0xf8, 0xd7, 0x29, 0xa6, 0x21, 0x36, 0x8d, 0x9c, 0x9f, 0xd1, 0x4f, 0xa1, 0x62, 0x54, 0xd5, 0xb0,
	0xc8, 0x99, 0xdf, 0x3c, 0xdc, 0xcd, 0xea, 0xa0, 0x62, 0x5f, 0x54, 0xcc, 0x35, 0x6e, 0x54, 0x36,
	0x5f, 0x41, 0x69, 0x6c, 0x2a, 0xeb, 0x14, 0xd5, 0xfc, 0xef, 0x65, 0x6a, 0x9f, 0xaa, 0xb8, 0x3b,
	0xd7, 0x90, 0xfd, 0x0a, 0xc6, 0x2c, 0xa5, 0x42, 0x8d, 0x4a, 0xc1, 0x35, 0xa7, 0xc6, 0x7f, 0x2c,
	0xa8, 0x7a, 0xd3, 0x8b, 0x54, 0x64, 0x45, 0x73, 0xa0, 0x68, 0x6a, 0x64, 0xd6, 0x21, 0x3b, 0xfe,
	0xcf, 0xa5, 0x5a, 0xb2, 0x9f, 0x5f, 0xb6, 0x8f, 0xbe, 0x5c, 0xcd, 0xb7, 0xa0, 0xf2, 0x75, 0xb2,
	0xc0, 0xb5, 0xdf, 0x07, 0x24, 0xbc, 0xfe, 0xad, 0x13, 0xfe, 0x0e, 0x6c, 0xb2, 0x89, 0xcf, 0xb1,
	0x48, 0x39, 0xf5, 0xa3, 0x40, 0x04, 0xe6, 0x7e, 0xa9, 0xb2, 0x89, 0xab, 0xc0, 0x56, 0x20, 0x82,
	0x46, 0x17, 0xea, 0x59, 0xf6, 0xc7, 0xe6, 0x46, 0x58, 0x64, 0x62, 0xad, 0x64, 0xf2, 0x0a, 0x6a,
	0x26, 0x13, 0x3d, 0x9d, 0x66, 0x68, 0xaa, 0x1a, 0xec, 0x29, 0xac, 0xf1, 0xef, 0x1c, 0xd4, 0x3d,
	0x1e, 0xd0, 0x24, 0x08, 0x05, 0x61, 0x34, 0xab, 0xe8, 0x2d, 0xe6, 0x09, 0x61, 0xd4, 0x5c, 0xbe,
	0xd9, 0x11, 0xfd, 0x00, 0x36, 0x88, 0xec, 0xb8, 0x1e, 0xed, 0xca, 0xe1, 0x76, 0x96, 0xdf, 0xd2,
	0x14, 0xbb, 0x46, 0x44, 0x4e, 0xce, 0x80, 0x50, 0x9f, 0xa9, 0x60, 0x13, 0x27, 0xaf, 0x34, 0x76,
	0x17, 0x1a, 0x2b, 0x59, 0xb8, 0x30, 0x20, 0x54, 0x23, 0x09, 0x3a, 0x80, 0x62, 0xa6, 0xb5, 0xae,
	0xb4, 0x76, 0xee, 0x6a, 0xe9, 0xad, 0x33, 0x42, 0xb2, 0xd1, 0x31, 0x0b, 0x6f, 0x7c, 0x41, 0xc6,
	0xba, 0x63, 0x35, 0xb7, 0x24, 0x01, 0x8f, 0x8c, 0xb1, 0x9c, 0x7d, 0x1d, 0x90, 0x1f, 0x52, 0xa1,
	0x6a, 0x5a, 0x73, 0xcb, 0x1a, 0x39, 0xa1, 0x42, 0xde, 0xf9, 0xc6, 0x8c, 0xe2, 0x8b, 0x8a, 0x07,
	0x03, 0x49, 0x81, 0x17, 0x00, 0x78, 0x2a, 0x78, 0xa0, 0x7b, 0x52, 0xd2, 0xbb, 0xa3, 0x10, 0xd9,
	0x10, 0xd9, 0xb6, 0x05, 0xed, 0xc7, 0x98, 0x9a, 0x1b, 0xab, 0x3a, 0x17, 0x79, 0x8b, 0x69, 0xe3,
	0x8f, 0x16, 0xec, 0x78, 0x53, 0x57, 0x2e, 0x55, 0x22, 0x5a, 0x58, 0x04, 0x24, 0xd6, 0x37, 0xed,
	0x2b, 0xa8, 0x71, 0x8d, 0x9a, 0xdd, 0xd5, 0x15, 0xaf, 0x1a, 0x50, 0xaf, 0xef, 0x2e, 0x14, 0xc5,
	0x74, 0x79, 0xf1, 0x37, 0xc4, 0x54, 0xad, 0xfd, 0x7d, 0xe7, 0xf9, 0xfb, 0xce, 0xe5, 0x85, 0xbd,
	0x24, 0xc5, 0xae, 0xaf, 0x13, 0x2c, 0x4c, 0x99, 0xea, 0x73, 0xc1, 0x0b, 0x05, 0x37, 0x7e, 0x6b,
	0xc1, 0xee, 0x3c, 0xd0, 0x3e, 0xe6, 0x24, 0x88, 0xc9, 0x07, 0x1c, 0xa9, 0x58, 0xbf, 0x0f, 0xf5,
	0xf9, 0x55, 0xb6, 0x12, 0xed, 0xe6, 0x1c, 0xd6, 0xf1, 0x3e, 0x87, 0xf2, 0x1c, 0x31, 0x11, 0x2f,
	0x00, 0x35, 0x97, 0x73, 0xc3, 0xbe, 0xd0, 0xd7, 0x95, 0x9c, 0xcb, 0x85, 0xb7, 0x69, 0xe3, 0x0f,
	0x16, 0x54, 0x3b, 0x11, 0xa6, 0x82, 0x88, 0x59, 0xf6, 0x1e, 0x50, 0xef, 0x04, 0xb3, 0xe4, 0xfa,
	0x80, 0x10, 0x14, 0xd2, 0x04, 0x73, 0xf3, 0x9d, 0x53, 0xbf, 0x25, 0x36, 0x62, 0x89, 0xde, 0xeb,
	0xb2, 0xab, 0x7e, 0x4b, 0x6c, 0xc2, 0xb8, 0xce, 0xba, 0xec, 0xaa, 0xdf, 0x0a, 0x0b, 0x84, 0xfe,
	0x74, 0x49, 0x2c, 0x10, 0x23, 0xe9, 0x45, 0x27, 0xa6, 0xe7, 0x44, 0x1f, 0xf6, 0xbf, 0xc9, 0x41,
	0xe5, 0x34, 0x20, 0x71, 0xca, 0xf5, 0xdb, 0xe4, 0x05, 0x3c, 0x31, 0x47, 0xff, 0x92, 0xe2, 0xe9,
	0x04, 0x87, 0x62, 0xfe, 0x11, 0xb3, 0xd7, 0xd0, 0x53, 0x78, 0x9c, 0xd1, 0xc7, 0xa9, 0x10, 0x8c,
	0xb6, 0x8d, 0x88, 0x9d, 0x43, 0x8f, 0x60, 0x2b, 0xe3, 0x64, 0xd5, 0xdb, 0x9c, 0x33, 0x6e, 0xe7,
	0xd1, 0x33, 0xd8, 0xcd, 0xe0, 0xa6, 0x5a, 0xc4, 0x93, 0x80, 0x86, 0x38, 0x8e, 0x71, 0x64, 0x17,
	0xd0, 0x2e, 0x6c, 0x67, 0x64, 0x8f, 0x2c, 0x8c, 0xad, 0x23, 0x07, 0x76, 0x96, 0x88, 0x85, 0xca,
	0x06, 0x7a, 0x0c, 0x68, 0x89, 0xe9, 0xd0, 0xdb, 0x20, 0x26, 0x91, 0x5d, 0x44, 0xcf, 0xc1, 0xc9,
	0x70, 0x03, 0xf6, 0xb3, 0xbe, 0xd8, 0xa5, 0x15, 0x7b, 0x9c, 0x85, 0x38, 0x49, 0x74, 0x7c, 0xe5,
	0xe5, 0x94, 0xba, 0x4c, 0xb4, 0x29, 0x4b, 0x87, 0xa3, 0xd3, 0x94, 0x46, 0x89, 0x0d, 0x77, 0xb8,
	0x0e, 0x25, 0xc2, 0xb4, 0xd1, 0xae, 0xa0, 0x27, 0xf0, 0x28, 0xe3, 0x4e, 0x09, 0x1f, 0xbf, 0x0f,
	0x38, 0xd6, 0x26, 0xc3, 0xfd, 0xdf, 0x5b, 0x60, 0xdf, 0xbd, 0x4e, 0x91, 0x0d, 0xd5, 0x5e, 0xf3,
	0x97, 0xde, 0x45, 0xb3, 0xd5, 0x72, 0xdb, 0xfd, 0xbe, 0xbd, 0x86, 0xb6, 0xa1, 0xae, 0x90, 0xfe,
	0x89, 0xdb, 0xe9, 0x79, 0x67, 0xcd, 0xfe, 0x99, 0x6d, 0xa1, 0x2d, 0xa8, 0x29, 0xf0, 0xfc, 0xf2,
	0xad, 0xd7, 0xe9, 0x77, 0xbe, 0xb6, 0x73, 0x73, 0xe8, 0xa2, 0xe7, 0xb6, 0xbd, 0x4b, 0xb7, 0x6b,
	0xe7, 0xe7, 0xc6, 0xde, 0x75, 0xbc, 0xae, 0x34, 0x56, 0x40, 0x3b, 0x60, 0x2b, 0xa4, 0x77, 0xd8,
	0x3f, 0xcb, 0xd0, 0xf5, 0xfd, 0x18, 0xea, 0x77, 0xbe, 0x63, 0x52, 0xb5, 0xdf, 0x6b, 0x77, 0x5b,
	0x8b, 0x38, 0xb6, 0xa0, 0xa6, 0x90, 0xb9, 0x4b, 0x0b, 0x55, 0xa1, 0xd4, 0xbe, 0xf2, 0xda, 0x6e,
	0xb7, 0xf9, 0xd6, 0xce, 0xcd, 0x55, 0x32, 0xbb, 0x79, 0xe9, 0x4d, 0x21, 0xcb, 0xde, 0x0a, 0xfb,
	0x97, 0x50, 0x31, 0xeb, 0xa5, 0x3c, 0x55, 0xa0, 0xe8, 0x5d, 0x75, 0xba, 0xbd, 0x4b, 0xcf, 0x5e,
	0x93, 0x16, 0xbd, 0xab, 0x8b, 0x4b, 0x4f, 0x9e, 0x2c, 0x04, 0xb0, 0xe1, 0x5d, 0x9d, 0xb7, 0xbd,
	0xa6, 0x9d, 0x43, 0x9b, 0x00, 0xde, 0xd5, 0x69, 0xa7, 0xdb, 0xe9, 0x9f, 0xb5, 0x5b, 0x76, 0x1e,
	0xd5, 0xa1, 0xe2, 0x5d, 0xb5, 0xaf, 0x3c, 0xb7, 0xd9, 0x6a, 0x7a, 0x4d, 0xbb, 0xb0, 0xff, 0xaf,
	0x1c, 0x6c, 0xe9, 0x69, 0x5b, 0xb6, 0xbe, 0x0b, 0xdb, 0x2b, 0xa0, 0x7f, 0x21, 0x46, 0x98, 0xdb,
	0x6b, 0xa8, 0x01, 0x9f, 0xad, 0x12, 0xa7, 0x18, 0x5f, 0xdc, 0x62, 0xee, 0x8d, 0x38, 0x4e, 0x46,
	0x2c, 0x96, 0xb3, 0xfa, 0x39, 0x3c, 0x5b, 0x95, 0x39, 0x61, 0xf4, 0x9a, 0xf0, 0xb1, 0xee, 0x9a,
	0x9d, 0x97, 0x7b, 0xb0, 0x2a, 0xe0, 0xe2, 0x04, 0x8b, 0x16, 0xbe, 0x25, 0x21, 0xb6, 0x0b, 0xf7,
	0x69, 0xa3, 0xff, 0x8e, 0x71, 0x39, 0xbd, 0xcf, 0xc1, 0x59, 0xa5, 0xdf, 0x91, 0x09, 0x36, 0xca,
	0x1b, 0xf7, 0x95, 0x7b, 0x9c, 0x09, 0x1c, 0x8a, 0x93, 0x20, 0x8e, 0xed, 0xa2, 0x1c, 0xd5, 0x55,
	0x5a, 0xce, 0xb1, 0x37, 0xb5, 0x4b, 0xf7, 0xa3, 0xce, 0x06, 0xef, 0x64, 0x84, 0xc3, 0x1b, 0xbb,
	0x2c, 0x67, 0x72, 0x55, 0xa0, 0xa9, 0xdf, 0x04, 0x36, 0xc8, 0x35, 0xbc, 0xe3, 0x34, 0x7b, 0xdb,
	0xdb, 0x95, 0xfd, 0xdf, 0xc0, 0x4e, 0x8f, 0xd0, 0xf3, 0x40, 0x70, 0x32, 0x5d, 0xae, 0xf1, 0x1e,
	0x3c, 0xff, 0x18, 0xee, 0x9f, 0xa4, 0x9c, 0x63, 0x2a, 0xec, 0x35, 0xf4, 0x12, 0x5e, 0x7c, 0x54,
	0xa2, 0x8b, 0xdf, 0x9f, 0x12, 0x9e, 0x08, 0x3b, 0x27, 0xfb, 0xf1, 0x29, 0x91, 0x3e, 0x0e, 0x19,
	0x8d, 0xec, 0xfc, 0xfe, 0xaf, 0x00, 0xb9, 0x38, 0x64, 0xb7, 0x98, 0xcf, 0x74, 0x99, 0x94, 0xfb,
	0xef, 0xc2, 0xcb, 0xfb, 0xa8, 0xdf, 0x0f, 0x79, 0x30, 0x1e, 0xc4, 0x38, 0x92, 0xc5, 0x4e, 0xec,
	0x35, 0x59, 0xcf, 0x8f, 0x88, 0x69, 0x87, 0xb6, 0xb5, 0x7f, 0x0d, 0x75, 0x29, 0xb9, 0x9c, 0xd7,
	0x13, 0x78, 0x74, 0x07, 0xf2, 0x7b, 0x71, 0x40, 0xa8, 0xbd, 0x26, 0xeb, 0x74, 0x97, 0xd2, 0x96,
	0xbe, 0xb4, 0xad, 0x4f, 0x93, 0x3f, 0xb1, 0x73, 0x47, 0x5f, 0x41, 0xf1, 0x3d, 0x51, 0x9f, 0x0f,
	0xf4, 0xf2, 0x40, 0xff, 0x27, 0x3c, 0xc8, 0xfe, 0x13, 0x1e, 0xb4, 0x69, 0x3a, 0xfe, 0x45, 0x10,
	0xa7, 0xf8, 0x62, 0x22, 0xef, 0xc0, 0xc4, 0xf9, 0xe6, 0x77, 0x79, 0xfd, 0x88, 0x97, 0x3a, 0x1d,
	0x7a, 0xf4, 0x33, 0x28, 0x29, 0x6d, 0x26, 0xff, 0xc6, 0xfc, 0x7f, 0xf5, 0xbf, 0x18, 0x75, 0xe5,
	0xf2, 0x22, 0x15, 0x47, 0x5f, 0x43, 0x4d, 0xe9, 0x47, 0x78, 0x90, 0x0e, 0x1f, 0x18, 0xc3, 0x5f,
	0x8d, 0x91, 0x8a, 0xd4, 0x6c, 0x49, 0xc5, 0x0e, 0x3d, 0xea, 0xc0, 0xe6, 0x92, 0xa1, 0x07, 0x86,
	0xf3, 0x37, 0x63, 0xa9, 0x3a, 0xb7, 0x24, 0x63, 0xfa, 0x39, 0x94, 0x95, 0x29, 0x41, 0xe8, 0xec,
	0x21, 0x56, 0xfe, 0x6e, 0xac, 0xa8, 0x4a, 0x78, 0x84, 0xce, 0x8e, 0xde, 0x42, 0x5d, 0x59, 0x18,
	0x30, 0x26, 0x62, 0xa6, 0xfe, 0x43, 0x3d, 0xc0, 0xce, 0x3f, 0x8c, 0x1d, 0x95, 0xc8, 0xf1, 0x5c,
	0xf5, 0xf8, 0x47, 0xf0, 0x2a, 0x64, 0xe3, 0x83, 0x24, 0x10, 0x2c, 0x19, 0x91, 0x38, 0x18, 0x24,
	0xd9, 0xe3, 0x2b, 0x26, 0x83, 0xb9, 0xbd, 0x63, 0xf0, 0x14, 0x28, 0xdb, 0x3b, 0xd8, 0x50, 0xe8,
	0x8f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x41, 0xc9, 0x77, 0xde, 0xfa, 0x0f, 0x00, 0x00,
}
